openapi: 3.0.0 #version of openAPI 3.0.0
info:
  title: Paycore API
  description: This is API for paycore project
  version: 1.0.0

servers:
  - url: '{protocol}://{domain}:{port}/{basePath}'
    description: This is url server
    variables:
      protocol:
        enum:
        - http
        - https
        default: http
      port:
        enum:
          - 8000
          - 80
        default: 8000
      basePath:
        default: api
      domain:
        default: paycore.local

paths:
  /login:
    $ref: '/js/api_docs/paths/auth.yaml#/~1login'
  /register:
    $ref: '/js/api_docs/paths/auth.yaml#/~1register'
  /me:
    deprecated: true
    $ref: '/js/api_docs/paths/auth.yaml#/~1me'
  /auth/me:
    $ref: '/js/api_docs/paths/auth.yaml#/~1auth~1me'
  /users:
    get:
      security:
        - bearerAuth: []
      tags:
        - User
      summary: Get list users.
      responses:
        '200':
          description: Get list users success.
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /users/show/{id}:
    get:
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/UserById'
      tags:
        - User
      summary: Get information of user by Id.
      responses:
        '200':
          description: Get information of user by Id success.
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        phone_number:
          type: string
        password:
          type: string
      required:
        - phone_number
        - password

  parameters:
    UserById:
      in: path
      name: id
      schema:
        type: integer
        required: true
      description: Input ID of user.

  responses:
    400Error:
      description: Invalid request.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: Requestion not found.
    UnauthorizedError:
      description: Access token is missing or invalid
