openapi: 3.0.0 #version of openAPI 3.0.0
info:
  title: Paycore API
  description: |

    This is api document for server project Paycore API.

    Design by:

        doanhuynguyenhong@gmail.com

  version: 1.0.0

servers:
  -
    url: '{protocol}://{domain}:{port}/{basePath}'
    description: This is url api
    variables:
      protocol:
        enum:
        - http
        - https
        default: http
      port:
        enum:
          - 8000
          - 80
        default: 8000
      basePath:
        default: api
      domain:
        enum:
          - paycore.local
          - 34.68.124.151
        default: paycore.local

paths:
  /login:
    $ref: '/js/api_docs/paths/auth.yaml#/~1login'
  /register:
    $ref: '/js/api_docs/paths/auth.yaml#/~1register'
  /me:
    deprecated: true
    $ref: '/js/api_docs/paths/auth.yaml#/~1me'
  /auth/me:
    $ref: '/js/api_docs/paths/auth.yaml#/~1auth~1me'
  /users:
    $ref: '/js/api_docs/paths/users.yaml#/~1users'
  /users/show/{id}:
    $ref: '/js/api_docs/paths/users.yaml#/~1users~1show~1{id}'

components:
  securitySchemes:
    bearerAuth:
      description: |
        For accessing the API a valid JWT token must be passed in all the queries in
        the 'Authorization' header.

        A valid JWT token is generated by the API and retourned as answer of a call
        to the route /login giving a valid user & password.

        The following syntax must be used in the 'Authorization' header :

            Value: xxxxxx.yyyyyyy.zzzzzz
        type: JWT
        name: Authorization
        in: header
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      $ref: '/js/api_docs/components/schemas.yaml#/User'
